Disable 'sse' optimization when compiling gf-complete
Add --disable-sse on configuration time to avoid to use the sse4
instructions.
Mason 32-bits is failing to compile gf-complete because it tries to
use this set of instructions which are specific for 64 bits machines,
showing the following error:

    gf_w128.c:393:5: error: incompatible types when assigning to type '__m128i' from type 'int'
    a = _mm_insert_epi64(prod, a128[1], 0x0);
      ^
    gf_w128.c:394:5: error: incompatible types when assigning to type '__m128i' from type 'int'
    a = _mm_insert_epi64(a, a128[0], 0x1);
      ^
    gf_w128.c:395:5: error: incompatible types when assigning to type '__m128i' from type 'int'
    b = _mm_insert_epi64(prod, b128[1], 0x0);
      ^
    gf_w128.c:396:5: error: incompatible types when assigning to type '__m128i' from type 'int'
    b = _mm_insert_epi64(b, b128[0], 0x1);
      ^

Change-Id: I5162cf7722f36925dd082f99478afdaf83d55b80