Use a version of Babel with Unicode CLDR included
Babel was failing with the following error:

  RuntimeError: The babel data files are not available. This usually
  happens because you are using a source checkout from Babel and you did
  not build the data files.  Just make sure to run "python setup.py
  import_cldr" before installing the library.

This commit fixes the problem.

Change-Id: I9b3fbe8ea2c9ead276271dfab831da8c3e2ae465