Update to latest Erlang (OTP-17.3.4)
The version in use before was failing to build with the following error:

    ...
    CC  /erlang.build/erts/obj/x86_64-unknown-linux-gnu/epmd_srv.o
    LD  /erlang.build/bin/x86_64-unknown-linux-gnu/epmd
    /erlang.build/erts/obj/x86_64-unknown-linux-gnu/epmd_srv.o: In function `run':
    /erlang.build/erts/epmd/src/epmd_srv.c:223: undefined reference to `sd_listen_fds'
    collect2: error: ld returned 1 exit status