Sometimes localhost doesn't resolve, so force 127.0.0.1
Sometimes localhost does not resolve, which makes rsync to
root@localhost fail during upgrades with:

ERROR: ssh-rsync.check failed with code 1: ERROR: Unable to SSH to
root@localhost: Command failed: ssh root@localhost -- true
ssh: connect to host localhost port 22: Connection timed out

So let's set the default to 127.0.0.1, which should always work.