mesa: Fix a compilation problem with missing fstat
Point mesa stratum to a patch cherry-picked from master to fix this
compilation error:

loader.c: In function 'udev_device_new_from_fd':
loader.c:163:4: error: implicit declaration of function 'fstat' [-Werror=implicit-function-declaration]
    if (fstat(fd, &buf) < 0) {
    ^
cc1: some warnings being treated as errors

More info here: https://bugs.freedesktop.org/show_bug.cgi?id=89530

Change-Id: I3bd4856b07318ce97772a4755b253c918f4b1e66